env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/dump"
    GH_TOKEN: "ENCRYPTED[ab10222fc943392bfcc9fbb0f474e165cbc0a77d11d187ea3d89958636895dcb27f80ddee52474b906175f273214d7c3]"
    TG_TOKEN: "ENCRYPTED[0ac6876fe59a0a91098381aba9e8fb5234bda72b9631631d38e78a8eae6004a449984223952dbdc8a06b9ebc25f6fba3]"
    GH_USERNAME: "P-Salik"
    GH_USEREMAIL: "peersalik16@gmail.com"
    FIRMWARE_LINK: "https://bigota.d.miui.com/V14.0.4.0.TKFMIXM/miui_SWEETGlobal_V14.0.4.0.TKFMIXM_8f4f7797e0_13.0.zip"

task:
    name: Dump
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 4
      memory: 16
    env_script:
      - env
    update_script:
      - apt-get update && apt-get upgrade -y
    setup_script:
      - set -evx
      - command=$(head $CIRRUS_WORKING_DIR/dumper.sh -n $(expr $(grep "\$GH_USEREMAIL" $CIRRUS_WORKING_DIR/dumper.sh -n | cut -d : -f1) + 1))
      - bash -c "$command"
    dump_script:
      - set -evx
      - command=$(head $CIRRUS_WORKING_DIR/dumper.sh -n $(expr $(grep "\$FIRMWARE_LINK" $CIRRUS_WORKING_DIR/dumper.sh -n | cut -d : -f1) + 1) | tail -n 5)
      - bash -c "$command"
