env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/dump"
    GH_TOKEN: "ENCRYPTED[b8cbdf555f0e00c6a5ed93616a71a4d07d7f3d5ee41d23b2da74cb066a044495271b0a90e08e48e4d9f8d3e607bfe027]"
    TG_TOKEN: "ENCRYPTED[b389e9456fe596268462a2da5814d91669a5b7d278eec624f74806339a4273169a37df6b2d800239e6ba89836b94a716]"
    GH_USERNAME: "P-Salik"
    GH_USEREMAIL: "peersalik16@gmail.com"
    FIRMWARE_LINK: "https://bigota.d.miui.com/V14.0.4.0.TKFMIXM/miui_SWEETGlobal_V14.0.4.0.TKFMIXM_8f4f7797e0_13.0.zip"

task:
    name: Dump
    timeout_in: 120m
    container:
      image: ubuntu:latest
      cpu: 4
      memory: 16
    env_script:
      - env
    update_script:
      - apt-get update && apt-get upgrade -y
    setup_script:
      - set -evx
      - command=$(head $CIRRUS_WORKING_DIR/dumper.sh -n $(expr $(grep "\$GH_USEREMAIL" $CIRRUS_WORKING_DIR/dumper.sh -n | cut -d : -f1) + 1))
      - bash -c "$command"
    dump_script:
      - set -evx
      - command=$(head $CIRRUS_WORKING_DIR/dumper.sh -n $(expr $(grep "\$FIRMWARE_LINK" $CIRRUS_WORKING_DIR/dumper.sh -n | cut -d : -f1) + 1) | tail -n 5)
      - bash -c "$command"
